#!/nix/store/gi8acxv619p85h4s2s8yl874hj66k8ig-lua-5.4.6/bin/lua

package.cpath = package.cpath .. ";/nix/store/61sdvzb8zqylx9f3qsj4b65rlymxvz4z-sbarlua-unstable/?.so"
-- sbar = require("sketchybar")
-- sbar.begin_config()

-- #!/usr/bin/env lua

-- This is only needed once to install the sketchybar module
-- (or for an update of the module)
-- os.execute("[ ! -d $HOME/.local/share/sketchybar_lua/ ] && (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)")

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- Require the sketchybar module
sbar = require("sketchybar")

-- Bundle the entire initial configuration into a single message to sketchybar
-- This improves startup times drastically, try removing both the begin and end
-- config calls to see the difference -- yeah..
sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()

-- Run the event loop of the sketchybar module (without this there will be no
-- callback functions executed in the lua module)
sbar.event_loop()
