# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
      kernelModules = [];
      luks.devices."luks-9885402b-5b7a-40d8-b363-35d3266d286f".device = "/dev/disk/by-uuid/9885402b-5b7a-40d8-b363-35d3266d286f";
    };
    kernelModules = ["kvm-amd" "sg"];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5444a920-397a-4dc5-9bd4-13a5ed3a6341";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5993-7A87";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/d0abffb7-9e1d-45a3-a586-800893b27087";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
