let g:vimsence_small_text = 'NeoVim'
let g:vimsence_small_image = 'neovim'
let g:vimsence_editing_state = ' '
let g:vimsence_editing_details = 'editing'
let g:vimsence_editing_large_text = 'yeeting a {} file'
