# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/caa4f203-3fa9-476e-bb56-05c23f3a2373";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/85e074b3-56c9-44a5-ab16-321956dce129"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
