name: cachix-nixos-ags
on:
  pull_request:
  push:
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: zachcoyle
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      # not enough storage on the github action runners...
      # - run: nix build .#nixosConfigurations.nixos-laptop.config.system.build.toplevel --show-trace
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.ags --show-trace
        continue-on-error: true
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.alacritty --show-trace
        continue-on-error: true
