name: cachix-nixos
on:
  pull_request:
  push:
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: zachcoyle
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#nixosConfigurations.nixos-laptop.config.system.build.toplevel --show-trace
      - run: nix build .#nixosConfigurations.nixos-desktop.config.system.build.toplevel --show-trace
