name: cachix-nixos
on:
  pull_request:
  push:
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      # - name: Set Swap Space
      #   uses: pierotofy/set-swap-space@master
      #   with:
      #     swap-size-gb: 0.1
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: zachcoyle
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.vscodium --show-trace
        continue-on-error: true
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.bruno --show-trace
        continue-on-error: true
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.nyxt --show-trace
        continue-on-error: true
