name: cachix-nixos
on:
  pull_request:
  push:
jobs:
  cachix:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 0.1
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: zachcoyle
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      # - run: nix build .#nixosConfigurations.nixos-laptop.config.system.build.toplevel --show-trace
      - run: nix build .#nixosConfigurations.nixos-laptop.config.boot.kernelPackages.kernel --show-trace
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.freecad --show-trace
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.rocmPackages.rocsolver --show-trace
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.neovim --show-trace
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.neovide --show-trace
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.ollama --show-trace
      - run: nix build .#nixosConfigurations.nixos-laptop.pkgs.hyprland --show-trace
    # - run: nix build .#nixosConfigurations.nixos-desktop.config.system.build.toplevel --show-trace
