name: cachix-darwin
on:
  pull_request:
  push:
jobs:
  cachix:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: zachcoyle
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#darwinConfigurations.mbp13.system --show-trace
      - run: nix build .#darwinConfigurations.mbp15.system --show-trace
